debian@debian:~/Downloads/system_administration$ su -
Password: 
root@debian:~# sudo adduser john_doe
Adding user `john_doe' ...
Adding new group `john_doe' (1001) ...
Adding new user `john_doe' (1001) with group `john_doe (1001)' ...
Creating home directory `/home/john_doe' ...
Copying files from `/etc/skel' ...
New password: 
Retype new password: 
passwd: password updated successfully
Changing the user information for john_doe
Enter the new value, or press ENTER for the default
        Full Name []:     
        Room Number []: 
        Work Phone []: 
        Home Phone []: 
        Other []: 
Is the information correct? [Y/n] y
Adding new user `john_doe' to supplemental / extra groups `users' ...
Adding user `john_doe' to group `users' ...
root@debian:~# sudo chsh -s /bin/bash john_doe
root@debian:~# sudo deluser --remove-home john_doe
Looking for files to backup/remove ...
Removing files ...
Removing crontab ...
Removing user `john_doe' ...
Done.
